name: Unit Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up python3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"
        architecture: "x64"
    - name: Update pip
      uses: python -m pip install --upgrade pip
    - name: Install project dependencies
      run : pip install -r requirements.txt
    - name: Run unit tests
      run: pytest -v

      